PR to add kubectl feature;important for installing providers
boldlink/terraform-helm-release pull request #3
Opened 2022-09-09 18:30 UTC by patrickmukumbu

# Description

PR to add kubectl feature;important for installing providers
## Features/Fixes/Patches/Changes list:

Please check the [CHANGELOG.md](https://github.com/boldlink/terraform-helm-release/blob/feature/kubectl-feature/CHANGELOG.md#110---2022-09-09)

## Checklists:

### PR Owners Checklist:
* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] Have you checked there aren't open [Pull Requests](../../../pulls) of upstream or parallel code that will cause conflicts?
* [ ] Have you updated the `CHANGELOG.md`?
* [ ] Have you updated the `README.md`(s)?
* [ ] OWNER: Does your submission pass?
    * [ ] Pre-commit (attach logs/print screen to this PR)
    * [ ] Checkov/terrascan (attach logs/print screen to this PR)
    * [ ] Terraform resources examples build/destroy successfully with Terraform 0.14.11 minimum?
* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] First PR? Have you deleted `## How to use this template...` from the root `.README.md`?

### PR Reviewers Checklists?
* [ ] Are all your comments/changes resolved?
* [ ] Are you happy with the OWNER checklists and additional information provided?
* [ ] Does your review tests pass?
    * [ ] Terraform resources examples build/destroy successfully with Terraform 0.14.11 minimum?

2022-09-11 18:16 UTC, hugoalmeida264 requested changes

2022-09-11 18:16 UTC, hugoalmeida264 commented on examples/complete/main.tf
> +      yaml_body = file("ngnx.yaml")
Should be `nginx`

2022-09-11 18:16 UTC, hugoalmeida264 commented on examples/complete/versions.tf
> +    kubectl = {
Why are we using this custom kubectl version? Doesnt the official one work?

2022-09-11 18:16 UTC, hugoalmeida264 commented on main.tf
> +resource "kubectl_manifest" "main" {
Why are we adding the kubectl manifest here?

2022-09-12 17:38 UTC, patrickmukumbu commented
Closing this PR because the feature is included as an ad-hoc resource in labs-platform

2022-09-12 17:38 UTC, closed without merging